name: CI

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
        
    - name: Restore packages
      run: nuget restore "src\Plaid Pad MIDI.sln"
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build
      run: msbuild "src\Plaid Pad MIDI.sln" -p:Configuration=Release
      
    - name: Publish
      run: msbuild "src\Plaid Pad MIDI.sln" -t:Publish -p:Configuration=Release
      
    - name: Create release
      uses: ncipolla/release-action@v1
      with:
        artifacts: "src/Mavanmanen.PPM/bin/Release/app.publish/**"
        token: ${{ secrets.GITHUB_TOKEN }}
